version: '3.8'
services:
  hkServer:
    container_name: hkserver
    image: lux00leo/hkserver:0.0.1
    depends_on:
      - hkdb
    ports:
      - 8080:8080
    networks:
      - front-tier
      - back-tier
  hkdb:
    container_name: hkdb
    image: lux00leo/hkdb:0.0.1
    expose:
      - 3306
    volumes:
      - C:\Users\5600G\Desktop\docker_volumes\test_mysql:/var/lib/mysql
    mem_limit: 256m
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: