import {departmentProject} from "@/app/lib/hk/domainsData";

export const PROJECT_IMG_PREFIX = '/hkdemo/domain_images/project_images';

export const projects: departmentProject[] = [
    {
        name: '낙동강 하굿둑 전망대동 내진보강공사 기술감리용역',
        startYear: '2018',
        projectOwner: '한국수자원공사',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '2019년 도로굴착복구공사 건설사업 관리용역(단가계약)',
        startYear: '2019',
        projectOwner: '부산광역시 해운대구청',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '별천지어린이공원 재해복구사업 건설사업관리 용역',
        startYear: '2019',
        projectOwner: '부산광역시 해운대구청',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '신정관로 일원 비탈면 보강공사 건설사업 관리용역',
        startYear: '2020',
        projectOwner: '부산광역시 기장군청',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '2020년 강서구 도로굴착복구 건설사업관리 용역',
        startYear: '2020',
        projectOwner: '부산광역시 강서구',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '부산항 신항 제2부두 유해화학물 장치장 설치공사 감리용역',
        startYear: '2020',
        projectOwner: '부산신항만주식회사',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '해운대 송정해수욕장간 연안정비사업 감독권한대행 등 건설사업관리용역(다릿돌전망대,해운대구청)',
        startYear: '2020',
        projectOwner: '부산광역시 해운대구청',
        hasImage: true,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '해운대 송정해수욕장간 연안정비사업 감독권한대행 등 건설사업관리용역(해월전망대,해운대구청)',
        startYear: '2020',
        projectOwner: '부산광역시 해운대구청',
        hasImage: true,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '목포내항 여객부두 건설공사 기본 및 실시설계 건설사업관리(설계단계)용역',
        startYear: '2021',
        projectOwner: '해양수산부 목포지방해양수산청',
        hasImage: true,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '2021년 상수도 급배수관 시설공사 건설사업관리용역(남부3권역)',
        startYear: '2021',
        projectOwner: '부산광역시',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '수영처리구역(수영강, 온천천4차) 오수관로 정비사업 건설사업관리용역',
        startYear: '2021',
        projectOwner: '부산광역시',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '수영처리구역(수영강, 온천천4차) 오수관로 정비사업 건설사업관리용역_2차',
        startYear: '2021',
        projectOwner: '부산광역시',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '2022년 상수도급배수관 시설공사 건설사업관리용역(해운대1권역)',
        startYear: '2022',
        projectOwner: '부산광역시',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '2023년 상수도 급배수관 시설공사 건설사업관리용역(남부1권역)',
        startYear: '2023',
        projectOwner: '부산광역시',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '2023년 상수도 급배수관 시설공사 건설사업관리용역(남부1권역)(2차)',
        startYear: '2023',
        projectOwner: '부산광역시',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '반여동 선수촌로 보행환경 개선사업 건설사업관리용역',
        startYear: '2023',
        projectOwner: '부산광역시 해운대구',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '학장2, 감전2지구 자연재해위험개선지구 정비사업 감독권한대행 등 건설사업관리용역(1차)',
        startYear: '2023',
        projectOwner: '부산광역시 사상구',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '부산항 신항 1부두(PNIT) 보안휄스 이전 및 승용주차장 확장공사 설게 및 감리용역',
        startYear: '2019',
        projectOwner: '부산신항국제터미널㈜',
        hasImage: false,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: '관',
    },
    {
        name: '강서구 기상청청사 신축공사 감리용역',
        startYear: '2019',
        projectOwner: '㈜종합건축사사무소 위고공간',
        hasImage: true,
        imageURL: '',
        departments: ['건설사업관리부'],
        projectOwnerType: "사",
    },
]